### ISSUE TITLE
Error creating file and project.

### ISSUE THREAD

**Issue by EndiKM** [CoreCoder-Devs/core-coder#15]
Hello, when I try to create a new file, I get such an error :

 TypeError: Cannot read property 'startsWith' of undefined at Object.getCompletions (file:///C:/Users/User/Desktop/CoreCoder/resources/app/src/util/Autocomplete.js:129:46) at file:///C:/Users/User/Desktop/CoreCoder/resources/app/lib/ace/ext-language_tools.js:1:30045 at Array.forEach () at l.gatherCompletions (file:///C:/Users/User/Desktop/CoreCoder/resources/app/lib/ace/ext-language_tools.js:1:30021) at l.updateCompletions (file:///C:/Users/User/Desktop/CoreCoder/resources/app/lib/ace/ext-language_tools.js:1:31267) at l.showPopup (file:///C:/Users/User/Desktop/CoreCoder/resources/app/lib/ace/ext-language_tools.js:1:30506) at Array.m (file:///C:/Users/User/Desktop/CoreCoder/resources/app/lib/ace/ext-language_tools.js:1:38499) at o.r._signal (file:///C:/Users/User/Desktop/CoreCoder/resources/app/lib/ace/ace.js:1:50300) at o.exec (file:///C:/Users/User/Desktop/CoreCoder/resources/app/lib/ace/ace.js:1:178336) at s.$callKeyboardHandlers (file:///C:/Users/User/Desktop/CoreCoder/resources/app/lib/ace/ace.js:1:63547)

This error shows up to me when creating the project :

 TypeError: Cannot read property 'style' of null at createProject (file:///C:/Users/User/Desktop/CoreCoder/resources/app/src/home.js:503:11) at HTMLButtonElement. (file:///C:/Users/User/Desktop/CoreCoder/resources/app/src/scripts/string_validator.js:142:13)

**Comment by Hanprogramer** [comment]
Thank you for reporting this error. The team will now look into this problem. If you have more details about the problem, please do share with us.

**Comment by skybird23333** [comment]
Hi, thanks for reporting this issue to us! Could you also please let us know the name of the file you were creating, as well as the folder you created it in?
