### ISSUE TITLE
Creating project which already exists should've warned instead

### ISSUE THREAD

**Issue by Hanprogramer** [CoreCoder-Devs/core-coder#17]
Error: EEXIST: file already exists, mkdir 'C:\Users\Hanprog\AppData\Local\Packages\Microsoft.MinecraftUWP_8wekyb3d8bbwe\LocalState/games/com.mojang\development_resource_packs\Tutorial RP' at mkdirSync (fs.js:845:3) at Object.fs.mkdirSync (electron/js2c/asar.js:718:16) at createProject (file:///D:/Programming/MinecraftProjects/github/CoreCoder-One/CoreCoder-One/src/home.js:530:12) at HTMLButtonElement. (file:///D:/Programming/MinecraftProjects/github/CoreCoder-One/CoreCoder-One/src/scripts/string_validator.js:142:13)

**Comment by skybird23333** [comment]
It does warn you, did you pull
