### ISSUE TITLE
Unhandled Promise Rejection Error

### ISSUE THREAD

**Issue by ThatJamGuy** [CoreCoder-Devs/core-coder#18]
When starting up CoreCoder and opening the projects I have and more I get an Unhandled Promise rejection error that says:
Unhandled Promise Rejection
TypeError: Cannot read property 'write' of null
    at IPCTransport.send (C:/Users/*****/Desktop/Addons Maker Tools/CoreCoder-v1.5.2-win32-x64/CoreCoder-win32-x64/resources/app/node_modules/discord-rpc/src/transports/ipc.js:151:17)
    at C:/Users/*****/Desktop/Addons Maker Tools/CoreCoder-v1.5.2-win32-x64/CoreCoder-win32-x64/resources/app/node_modules/discord-rpc/src/client.js:166:22
    at new Promise (<anonymous>)
    at RPCClient.request (C:/Users/*****/Desktop/Addons Maker Tools/CoreCoder-v1.5.2-win32-x64/CoreCoder-win32-x64/resources/app/node_modules/discord-rpc/src/client.js:164:12)
    at RPCClient.setActivity (C:/Users/*****/Desktop/Addons Maker Tools/CoreCoder-v1.5.2-win32-x64/CoreCoder-win32-x64/resources/app/node_modules/discord-rpc/src/client.js:529:17)
    at Object.setActivity (C:/Users/*****/Desktop/Addons Maker Tools/CoreCoder-v1.5.2-win32-x64/CoreCoder-win32-x64/resources/app/src/util/DiscordRPC.js:17:14)
    at IpcMainImpl.<anonymous> (C:/Users/*****/Desktop/Addons Maker Tools/CoreCoder-v1.5.2-win32-x64/CoreCoder-win32-x64/resources/app/main.js:28:7)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:157:8362)

I've tried multiple times to locate the source of the error and fix it but I've had no luck. Can anyone explain what this means and how to deal with it?

**Comment by skybird23333** [comment]
thats normal and is related to discord rich presence, it should still work
